### ISSUE TITLE
Als Entwickler möchte ich eine Grundstruktur haben um weitere Features zu implementieren (Serverseitig)

### ISSUE THREAD

**Issue by MartinR2295** [SE2-Gamma/carcassonne#19]

**Comment by MartinR2295** [comment]
Alternative to RMI with Sockets:

1. Client connect to server
2. There are different commands:
-- setuser Max: set username
-- join: join to session, which isn't started yet (lobby state)
-- create: create a new session (lobby state)

lobby state:
-- exit
-- start (only available for creator) (when start, all users move to gamestate)
-- kick username (only available for creator)

gamestate
server write each round, which player needs to play
-- exit
-- play (sends a play object (place of card, orientation and location of figures)) after that, the server send a game object update, and the request for the next player.

**Comment by bthaus** [comment]
Liste von Payload Objects:
CreateGameCommand: 
  //Payload = LinkedList<Object>
    //1. entry: String GameID (gamename)
    //2. entry: Player player (der PLayer wird auch zur session hinzugefügt)
    //
    //serverResponseCommand payload=Session
InitialJoinCommand:
//Payload= linked List
    //entry1= Player
    //entry2= SessionID
    //
    //return= ServerResponseCOmmand
InitialSetNameCommand:
//Payload = Player (name in player gespeichert)
